### ISSUE TITLE
Exclude not working correctly with typescript 1.8.2

### ISSUE THREAD

**Issue by golear91** [TypeStrong/grunt-ts#338] opened 2016-02-24 21:31 UTC
with typescript 1.7.5 works fine:
![image](https://cloud.githubusercontent.com/assets/16123225/13301599/8f912d04-dafa-11e5-953f-35fe6d7228c3.png)
When I upgrade to 1.8.2 it fails:
![image](https://cloud.githubusercontent.com/assets/16123225/13301639/c64fbde2-dafa-11e5-9122-1ac4873deee4.png)
Looks like the exclude directory is not working correctly.
Edit:
I am using a tsconfig.json file:

    {
    "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "rootDir": "app",
    "outDir": "dist"
    },
    "exclude": [
    "node_modules",
    "bower_components",
    "typings/main",
    "typings/main.d.ts"
    ]
    }

**Comment by errorx666** [comment] 2016-02-24 22:59
I'm trying to reproduce this issue, as I recently worked on the exclude code.  I'm having some trouble getting the same results.

@golear91
What platform are you running on?  (This shouldn't matter but the path separator difference can be a factor.)

Are you using the version of `grunt-ts` from the npm repository, or from the `master` branch?

Is there a repository I can clone that will reproduce the issue?

**Comment by pramodsankarl** [comment] 2016-02-25 01:20
I was about to post the same issue when i saw it has been logged already. :)

**Comment by golear91** [comment] 2016-02-25 01:55
@errorx666 yeah I saw that you fixed the other issue I was running into (being unable to exclude files), but I am still running the npm version, not the latest from master.
additional details:
- windows 10
- grunt 0.4.5
- grunt-ts 5.3.1
- typescript 1.7.5 (works) 1.8.2 (doesn't)

The repo I'm working in is private so sorry can't provide you access to clone.

It seems like the generated tsconfig.json has items in the `"files"` array that should be excluded, and from the [documentation ](https://github.com/TypeStrong/grunt-ts#tsconfig)it looks like `"exclude"` is ignored when `"files"` is specified

**Comment by errorx666** [comment] 2016-02-25 03:41
@pramodsankarl @golear91
Can you `npm install https://github.com/errorx666/grunt-ts/tarball/exclude-files`, and see if the issue is resolved already?
(I wouldn't keep using that version, but I want to verify the issue still exists.)

**Comment by pramodsankarl** [comment] 2016-02-25 14:32
@errorx666  Yes this works fine. Thank you. I cannot use this as is however. Would you be able to get this out sooner?

**Comment by errorx666** [comment] 2016-02-25 15:36
@pramodsankarl I have a PR open for that branch.  Hopefully it will make it into the next NPM release.  I'm not a member of TypeStrong so I have no control over that.

**Comment by golear91** [comment] 2016-02-25 22:18
hmm I'm still having issues after install fro the url above
package.json:

    "devDependencies": {
    "concurrently": "^1.0.0",
    "grunt": "^0.4.5",
    "grunt-chrome-manifest": "^0.3.0",
    "grunt-contrib-clean": "^1.0.0",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-copy": "^0.8.2",
    "grunt-contrib-cssmin": "^0.14.0",
    "grunt-contrib-htmlmin": "^0.6.0",
    "grunt-contrib-uglify": "^0.11.1",
    "grunt-filerev": "^2.3.1",
    "grunt-ts": "https://github.com/errorx666/grunt-ts/tarball/exclude-files",
    "grunt-usemin": "^3.1.1",
    "lite-server": "^2.0.1",
    "load-grunt-tasks": "^3.4.0",
    "typescript": "^1.8.2",
    "typings": "^0.6.8"
    }

the `grunt-ts` task just uses my tsconfig.json file:

    {
    "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "rootDir": "app",
    "outDir": "dist"
    },
    "exclude": [
    "node_modules",
    "bower_components",
    "typings/main",
    "typings/main.d.ts"
    ]
    }

And I get the same error:
![image](https://cloud.githubusercontent.com/assets/16123225/13336395/9844433e-dbca-11e5-8685-1717b2c9aa25.png)

**Comment by pramodsankarl** [comment] 2016-02-26 19:36
@errorx666 Thank you. I am using passthrough option for now until the next upgrade with the fix. @golear91 Does running `tsc` command directly to compile work for you?

**Comment by golear91** [comment] 2016-02-26 19:47
@pramodsankarl yup it works perfect, no Issues

**Comment by MartinMa** [comment] 2016-03-04 10:43
I'm having the exact same issue using `grunt-ts@5.3.2` on a Windows 8.1 machine.
The configuration in my `Gruntfile.js` looks like this
```
ts: {
    default : {
      tsconfig: true
    }
  }
```

And tsconfig.js looks like this
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

It starts compiling, but stumbles upon files in the "excluded" folders. It also emits `Using tsc v1.8.7`.

@golear91 What exactly is the workaround? Passthrough? You mean calling tsc directly from the node_modules folder using grunt-shell?

**Comment by pramodsankarl** [comment] 2016-03-04 17:32
@MartinMa You can try this configuration for now if you are also facing duplicate def errors (and keep your exclude in `tsconfig.json`):

```
{
    options: {
      'compiler': './node_modules/typescript/bin/tsc'
    },
    default: {
       tsconfig: {
         passThrough : true
       }
    }
  }
```

**Comment by golear91** [comment] 2016-03-04 21:40
@MartinMa let me know if @pramodsankarl fix works for you, if not I can detail what I have done.

**Comment by MartinMa** [comment] 2016-03-07 08:31
Thank you both, the method described by @panuhorsmalahti works without problems.

**Comment by nicojs** [comment] 2016-03-22 15:59
Have the same issue, @errorx666 's version is working for me:
https://github.com/errorx666/grunt-ts/tarball/exclude-files :+1:

**Comment by errorx666** [comment] 2016-03-22 18:27
@nicojs That branch was merged to master here.  You should not keep using it; I won't be maintaining it.

**Comment by nicojs** [comment] 2016-03-22 21:39
But is there already a release? I don't think so. I still get the errors with the `5.3.2` release (published 2 months ago)

**Comment by nycdotnet** [comment] 2016-03-22 22:39
I expect to publish in the next day or so.  Thanks for your patience.

**Comment by nycdotnet** [comment] 2016-03-23 03:44
This should be published in v5.4.0 - just published to npm.  Please let me know if you have further issues.  Thanks for the PRs, @errorx666 , and thanks to everyone else who provided feedback. :smile:

**Closed by nycdotnet** 2016-03-23 03:44 UTC

**Comment by nicojs** [comment] 2016-03-23 07:38
:+1:  works like a charm! Thanks everyone

**Comment by irejwanul** [comment] 2016-11-17 10:24
Hi, If you can add "files" section, can be an empty array as well. 
Like, "exclude": [ "node_modules" ],
"files": []
This should now exclude files or path defined in "exclude" section.
In my case this solution worked fine.
Thanks everyone
