### ISSUE TITLE
Question: Is it possible to override outFile command from loaded tsconfig

### ISSUE THREAD

**Issue by jkanchelov** [TypeStrong/grunt-ts#409] opened 2017-08-25 12:16 UTC
Hello, guys. I bumped in some trouble loading a tsconfig and then for different builds trying to change the out ( outFile ) destination through grunt-ts. Is it possible to be done? 

I want to do something like that 
```
        debug: {
            tsconfig: './tsconfig.json',
            out: "./debug",
        },
        release: {
            tsconfig: './tsconfig.json',
            out: "./release",
        }
```

Thanks in advance for the help.

**Comment by AHaberl** [comment] 2017-09-21 13:18
+1

**Comment by nycdotnet** [comment] 2018-03-13 14:31
Hi - sorry for not responding sooner.  This is how this is intended to work, and I believe this is a bug.

**Comment by nycdotnet** [comment] 2018-03-13 16:10
Should be fixed in v6.0.0-beta.19

**Closed** 2018-03-13 16:10 UTC
Labels: bug

**Comment by nycdotnet** [comment] 2018-03-13 16:11
Thanks for the report - this was a stupid copy and paste bug and I didn't have a test for the expected behavior.
