### ISSUE TITLE
grunt-ts not respecting "exclude" in tsconfig

### ISSUE THREAD

**Issue by golear91** [TypeStrong/grunt-ts#334] opened 2016-02-23 00:41 UTC
I am using a tsconfig.json file in conjunction with grunt-ts here is the grunt task:

    ts: {
        default: {
        tsconfig: true
      }

and the tsconfig.json file:

    {
      "compilerOptions": {
        "target": "es5",
        "module": "system",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false,
        "rootDir": "app",
        "outDir": "dist"
      },
      "exclude": [
        "node_modules",
        "bower_components",
        "typings/main",
        "typings/main.d.ts"
      ]
    }

When I try to run this grunt task I get an error TS2300 from duplicate identifiers.  the `exclude: "typings/main"` is meant to avoid this, and it works when running tsc from the command line, but not when running the grunt-ts task. Somewhat confused as it is definitely excluding `node_modules` in the compilation, but not the typings file.

**Comment by basarat** [comment] 2016-02-23 00:49
Duplicate of https://github.com/TypeStrong/grunt-ts/issues/285 . Feel free to jump in and help :rose:

**Closed** 2016-02-23 00:49 UTC
Labels: duplicate
